name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     contents: read

  #   environment: ${{ github.ref == 'refs/heads/main' && 'prod' || (github.ref == 'refs/heads/dev' && 'dev') || github.ref == 'refs/heads/test' && 'test' }}

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install oc CLI
  #       uses: redhat-actions/oc-installer@v1

  #     - name: Authenticate and set context for OpenShift
  #       uses: redhat-actions/oc-login@v1
  #       with:
  #         openshift_server_url: ${{ vars.OPENSHIFT_SERVER }}
  #         namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
  #         openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
  #         insecure_skip_tls_verify: true

  #     - name: Run Helm upgrade
  #       run: |
  #         helm upgrade --install cappy ./helm --set image.tag=${{ needs.build.outputs.image_tag }}

  #     - name: Trigger OpenShift Rollout
  #       run: |
  #         oc rollout restart deployment/cappy