apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: metabase-to-postgres
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: metabase
    ports:
    - protocol: TCP
      port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: metabase-egress
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: metabase
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - {}
